name: "test -> build -> update lib if needed"
on:
  push:
    branches:
      - '**'
    tags:
      - '!**' # prevent running it for tags
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - uses: actions/setup-node@v1
        name: setup node
        with:
          node-version: '16.x'

      - name: "install"
        run: npm ci --production

      - name: "build"
        run: npm i -g @vercel/ncc && npm run build

      - name: "check if build has changed"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        if: success()
        id: has-changes
        run: echo ::set-env name=LIB_DIFF::$(git diff  --stat -- 'lib') # cause bundle is located in lib folder

      - name: "Commit files"
        if: ${{ env.LIB_DIFF }}
        run: |
          git config --local user.email "sharfull33@gmail.com" # fake user email for pushing build
          git config --local user.name "Build action bot"
          git commit -m "build action" -a
      - name: "Push changes"
        if: ${{ env.LIB_DIFF }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}.  # push to the same branch